env:
 # we have to use CABALVER=1.16 for GHC<7.6 as well, as there's
 # no package for earlier cabal versions in the PPA
 - GHCVER=7.4.1 CABALVER=1.16
 - GHCVER=7.4.2 CABALVER=1.16
 - GHCVER=7.6.3 CABALVER=1.16
 - GHCVER=7.8.3 CABALVER=1.18
 - GHCVER=head  CABALVER=head

matrix:
  allow_failures:
   - env: GHCVER=head  CABALVER=head

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - cabal --version

install:
 - travis_retry cabal update
 - cabal install --enable-tests --only-dependencies
 - ghc --version

script:
 - autoreconf -i
 - cabal configure -v2 --enable-tests
 - cabal build
 - cabal check
 - cabal sdist
 - cabal test --show-details=streaming --test-options=WAY=
 - cabal install --force-reinstalls --run-tests dist/*-*.tar.gz
